# Generated by Django 4.1.2 on 2024-06-20 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.IntegerField(db_column='id_empresa', primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido_paterno', models.CharField(max_length=80)),
                ('apellido_materno', models.CharField(max_length=80)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('telefono', models.IntegerField(verbose_name=9)),
                ('id_empresa_asociada', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, to='clientes.empresa')),
            ],
        ),
    ]
